# Generated by Selenium IDE
import os

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class wait_till_download_complete:
    def __init__(self, path):
        self._path = path

    def __call__(self, driver):
        if os.path.isfile(self._path):
            return True
        else:
            return False


class TIS():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_tis(self, username, password, year):
        file_name = 'XXX' + username[3:-1] + 'X' + "_" + year + "_" + "TIS.pdf"

        self.vars = {}
        options = Options()
        PATH = os.path.abspath("tb-downloads") + "\\"
        prefs = {"download.default_directory": PATH}
        options.add_experimental_option("prefs", prefs)
        # options.add_argument('--headless')  # Run Chrome in headless mode
        # options.add_argument('--no-sandbox')
        # options.add_argument('--disable-dev-shm-usage')
        self.driver = webdriver.Chrome(options=options)
        self.driver.maximize_window()
        self.driver.get("https://eportal.incometax.gov.in/iec/foservices/")
        # self.driver.set_window_size(1536, 824)
        self.driver.find_element(By.ID, "panAdhaarUserId").click()
        self.driver.find_element(By.ID, "panAdhaarUserId").send_keys(username)
        self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary > span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".mat-checkbox-label").click()
        self.driver.find_element(By.ID, "loginPasswordField").click()
        self.driver.find_element(By.ID, "loginPasswordField").send_keys(password)
        self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".primaryButton").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "#navBar-\\ 3 > .mat-button-wrapper")))
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#navBar-\\ 3 > .mat-button-wrapper").click()
        # 19 | waitForElementVisible | xpath=//div[@id='cdk-overlay-8']/div/div/span[5]/span/div/button/span | 30000
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located(
                (By.XPATH, "//*[@id=\"cdk-overlay-8\"]/div/div/span[5]/span/div/button")))
        self.driver.find_element(By.XPATH, "//*[@id=\"cdk-overlay-8\"]/div/div/span[5]/span/div/button").click()
        # 21 | waitForElementEditable | id=okBtnNav3 | 30000
        WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.ID, "okBtnNav3")))
        # 22 | click | id=okBtnNav3 |
        self.vars["window_handles"] = self.driver.window_handles
        # 23 | selectWindow | handle=${aisportal} |
        self.driver.find_element(By.ID, "okBtnNav3").click()
        # 24 | pause | 3000 |
        self.vars["aisportal"] = self.wait_for_window(10000)
        # 25 | click | css=.opacity-6:nth-child(2) |
        self.driver.switch_to.window(self.vars["aisportal"])
        # 26 | waitForElementVisible | css=div:nth-child(2) > img | 30000
        time.sleep(5)
        # 27 | click | css=div:nth-child(2) > img |
        self.driver.find_element(By.CSS_SELECTOR, ".opacity-6:nth-child(2)").click()
        # 28 | waitForElementVisible | css=.btn-outline-primary | 30000
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "div:nth-child(2) > img")))
        # 29 | click | css=.btn-outline-primary |
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > img").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn-outline-primary")))
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-primary").click()
        if os.path.exists(os.path.abspath("tb-downloads") + "\\" + file_name):
            os.remove(os.path.abspath("tb-downloads") + "\\" + file_name)
        time.sleep(2)
        WebDriverWait(self.driver, 30).until(
            wait_till_download_complete(os.path.abspath("tb-downloads") + "\\" + file_name))
        return os.path.abspath("tb-downloads") + "\\" + file_name

if __name__ == '__main__':
    TIS().test_tis("AAFCM4979A", "SRSHAH@211050", "2022-23")
