# Generated by Selenium IDE
import os.path

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.core.files.storage import default_storage


class wait_till_download_complete:
    def __init__(self, path):
        self._path = path

    def __call__(self, driver):
        if os.path.isfile(self._path):
            return True
        else:
            return False


class TestForm26as():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_form26as(self, username, password, year):
        self.vars = {}
        options = Options()
        PATH = os.path.abspath("tb-downloads") + "\\"
        prefs = {"download.default_directory": PATH}
        options.add_experimental_option("prefs", prefs)
        options.add_argument('--headless')  # Run Chrome in headless mode
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        self.driver = webdriver.Chrome(options=options)
        self.driver.maximize_window()
        self.driver.get("https://eportal.incometax.gov.in/iec/foservices/")
        # self.driver.set_window_size(1536, 824)
        self.driver.find_element(By.ID, "panAdhaarUserId").click()
        self.driver.find_element(By.ID, "panAdhaarUserId").send_keys(username)
        self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary > span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".mat-checkbox-label").click()
        self.driver.find_element(By.ID, "loginPasswordField").click()
        self.driver.find_element(By.ID, "loginPasswordField").send_keys(password)
        self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".large-button-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".primaryButton").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "#navBar-\\ 1 > .mat-button-wrapper")))
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#navBar-\\ 1 > .mat-button-wrapper").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located(
                (By.XPATH, "//*[@id=\"cdk-overlay-8\"]/div/div/span[1]/span/div/button")))
        self.driver.find_element(By.XPATH, "//*[@id=\"cdk-overlay-8\"]/div/div/span[1]/span/div/button").click()
        self.driver.find_element(By.XPATH, "//*[@id=\"cdk-overlay-9\"]/div/div/span[4]/span/button").click()
        self.vars["window_handles"] = self.driver.window_handles
        WebDriverWait(self.driver, 30).until(
            expected_conditions.element_to_be_clickable(
                (By.ID, "okBtnNav1")))
        self.driver.find_element(By.ID, "okBtnNav1").click()
        self.vars["win1044"] = self.wait_for_window(5000)
        self.driver.switch_to.window(self.vars["win1044"])
        element = self.driver.find_element(By.XPATH, "//ul[@id=\'cssdropdown\']/li/div/a/span[2]")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "View Form 26AS/Annual Tax Statement").click()
        self.driver.find_element(By.ID, "AssessmentYearDropDown").click()
        dropdown = self.driver.find_element(By.ID, "AssessmentYearDropDown")
        dropdown.find_element(By.XPATH, "//option[. = '" + year + "']").click()
        self.driver.find_element(By.ID, "viewType").click()
        dropdown = self.driver.find_element(By.ID, "viewType")
        dropdown.find_element(By.XPATH, "//option[. = 'HTML']").click()
        self.driver.find_element(By.ID, "btnSubmit").click()
        if os.path.exists(os.path.abspath("tb-downloads") + "\\" + username + "-" + year[0:4] + ".pdf"):
            os.remove(os.path.abspath("tb-downloads") + "\\" + username + "-" + year[0:4] + ".pdf")
        self.driver.find_element(By.ID, "pdfBtn").click()
        WebDriverWait(self.driver, 30).until(
            wait_till_download_complete(os.path.abspath("tb-downloads") + "\\" + username + "-" + year[0:4] + ".pdf"))
        return os.path.abspath("tb-downloads") + "\\" + username + "-" + year[0:4] + ".pdf"
# if __name__ == '__main__':
#     TestForm26as().test_form26as("AAFCM4979A", "SRSHAH@211050", "2022-23")
